# Copyright © SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "crud"
version = "0.2.2"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"

[[bin]]
path = "main.rs"
name = "crud"

[dependencies]
slint = { path = "../../../api/rs/slint" }
